# Site wide configuration

title: "A Coming Soon"
description: "A Coming Soon"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: Toshiyuki Takenaka

#Target date in UTC / GMT
countdown:
  theme: black
  year: 2017
  month: 3
  day: 1
  hour: 0
  minute: 0

# Site owner
owner:
  name: Toshiyuki Takenaka
  email: takenaka@attitude-toward.com
  twitter: "https://twitter.com/takenakanda"
  google-plus:
  instagramm: "https://www.instagram.com/takenakanda"
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
